# Generated by Django 4.0.3 on 2022-04-15 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_rename_img_id_comment_image_rename_img_id_like_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
    ]
